"""End-to-end: a Telnyx recording webhook becomes a spec-valid vCon.

The BYOK product ingests over the Telnyx API rather than a SIPREC fork, so this
path *is* the product. Nothing else in the suite exercised it: `test_webhook.py`
mocks the builder out entirely and asserts on a `MagicMock`, which is why a vCon
that failed `is_valid()` shipped unnoticed.

Here the real builder runs against real audio bytes and the resulting vCon is
inspected. No network: `requests.get` is patched to serve a WAV generated by the
stdlib.
"""

import io
import wave
from unittest.mock import MagicMock, patch

import pytest
from fastapi.testclient import TestClient

from adapters.telnyx import TelnyxConfig, create_app
from adapters.telnyx.builder import TelnyxRecordingData, TelnyxVconBuilder

FROM_NUMBER = "+15085550101"
TO_NUMBER = "+16175550102"


def wav_bytes(seconds: int = 1, rate: int = 8000) -> bytes:
    """A real, tiny, deterministic WAV. Beats committing a fixture file."""
    buf = io.BytesIO()
    with wave.open(buf, "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(rate)
        w.writeframes(b"\x00\x01" * rate * seconds)
    return buf.getvalue()


@pytest.fixture
def recording_event():
    """A `call.recording.saved` shaped like Telnyx's documented payload."""
    return {
        "data": {
            "event_type": "call.recording.saved",
            "id": "evt-1",
            "occurred_at": "2026-09-09T18:00:05Z",
            "payload": {
                "call_control_id": "v3:abc123",
                "call_leg_id": "leg-1",
                "call_session_id": "sess-1",
                "connection_id": "conn-1",
                "recording_id": "rec-1",
                "recording_urls": {
                    "wav": "https://api.telnyx.com/v2/recordings/rec-1.wav",
                    "mp3": "https://api.telnyx.com/v2/recordings/rec-1.mp3",
                },
                "channels": "dual",
                "duration_millis": 1000,
                "from": FROM_NUMBER,
                "to": TO_NUMBER,
                "direction": "incoming",
                "start_time": "2026-09-09T18:00:00Z",
            },
        }
    }


@pytest.fixture
def audio_response():
    """Patch the recording download to serve real WAV bytes."""
    response = MagicMock()
    response.content = wav_bytes()
    response.status_code = 200
    response.raise_for_status = MagicMock()
    with patch("adapters.telnyx.builder.requests.get", return_value=response):
        yield response


@pytest.fixture
def built_vcon(recording_event, audio_response):
    """The vCon the real builder produces from that event."""
    builder = TelnyxVconBuilder(
        download_recordings=True, recording_format="wav", api_key="test-key"
    )
    vcon = builder.build(TelnyxRecordingData(recording_event))
    assert vcon is not None, "builder returned None"
    return vcon


# -- the vCon itself -------------------------------------------------------


def test_vcon_is_spec_valid(built_vcon):
    """The acceptance criterion for CON-844.

    Regression guard for the `mimetype` vs `mediatype` bug: `core/base_builder`
    passed the non-spec `mimetype`, so vcon-lib's validator rejected every vCon
    every adapter in this monorepo produced.
    """
    valid, errors = built_vcon.is_valid()
    assert valid, f"vCon failed spec validation: {errors}"


def test_dialog_carries_mediatype_not_mimetype(built_vcon):
    dialog = built_vcon.to_dict()["dialog"][0]
    assert dialog.get("mediatype") == "audio/wav"
    assert "mimetype" not in dialog, "non-spec field is back"


def test_syntax_version_is_core_02(built_vcon):
    assert built_vcon.to_dict()["vcon"] == "0.4.0"


def test_both_parties_present_as_tel_uris(built_vcon):
    tels = [p.get("tel") for p in built_vcon.to_dict()["parties"]]
    assert tels == [FROM_NUMBER, TO_NUMBER]


def test_audio_is_embedded_and_decodes(built_vcon):
    """A dialog that claims base64 audio should actually contain a WAV."""
    import base64

    dialog = built_vcon.to_dict()["dialog"][0]
    assert dialog["encoding"] == "base64"
    raw = base64.b64decode(dialog["body"])
    assert raw[:4] == b"RIFF" and raw[8:12] == b"WAVE", "body is not a WAV"


def test_duration_converted_from_millis(built_vcon):
    assert built_vcon.to_dict()["dialog"][0]["duration"] == 1.0


def test_inbound_call_originates_from_callee(built_vcon):
    """Telnyx `incoming` means they called us, so party 1 initiated."""
    assert built_vcon.to_dict()["dialog"][0]["originator"] == 1


def test_telnyx_identifiers_are_preserved(built_vcon):
    """Correlating a vCon back to the call requires these to survive."""
    tags = built_vcon.to_dict()["attachments"][0]["body"]
    assert "telnyx_call_session_id:sess-1" in tags
    assert "telnyx_call_control_id:v3:abc123" in tags
    assert "recording_channels:dual" in tags


@pytest.mark.xfail(
    strict=True,
    reason="CON-814: core/base_builder writes no attachments, so no adapter in "
    "this monorepo emits a lawful_basis. Blocking for customer deployment. "
    "When that is fixed, this passes and the marker should be removed.",
)
def test_vcon_carries_a_lawful_basis(built_vcon):
    assert built_vcon.find_lawful_basis_attachments(), "no lawful_basis attachment"


# -- through the webhook ---------------------------------------------------


def test_webhook_posts_a_valid_vcon_to_the_conserver(
    recording_event, audio_response, monkeypatch, tmp_path
):
    """The whole BYOK loop, minus Telnyx itself.

    Unlike `test_webhook.py`, the builder is real here; only the outbound post is
    captured, so this asserts on the vCon that would actually reach the conserver.
    """
    monkeypatch.setenv("CONSERVER_URL", "http://conserver.test")
    monkeypatch.setenv("VALIDATE_TELNYX_WEBHOOK", "false")
    # Isolate the dedupe state. Without this the tracker picks up whatever
    # `.telnyx_adapter_state.json` is lying in the working directory and skips
    # `rec-1` as already processed, which passes alone and fails in a full run.
    monkeypatch.setenv("STATE_FILE", str(tmp_path / "state.json"))

    posted = []
    with patch("adapters.telnyx.webhook.HttpPoster") as poster_cls:
        poster = MagicMock()
        poster.post.side_effect = lambda v: (posted.append(v), True)[1]
        poster_cls.return_value = poster

        client = TestClient(create_app(TelnyxConfig()))
        response = client.post("/webhook/recording", json=recording_event)

    assert response.status_code == 200
    assert len(posted) == 1, "exactly one vCon should have been posted"

    valid, errors = posted[0].is_valid()
    assert valid, f"the vCon sent to the conserver is not spec-valid: {errors}"
