"""End-to-end: a Telnyx recording webhook becomes a spec-valid vCon.

The BYOK product ingests over the Telnyx API rather than a SIPREC fork, so this
path *is* the product. Nothing else in the suite exercised it: `test_webhook.py`
mocks the builder out entirely and asserts on a `MagicMock`, which is why a vCon
that failed `is_valid()` shipped unnoticed.

Here the real builder runs against real audio bytes and the resulting vCon is
inspected. No network: `requests.get` is patched to serve a WAV generated by the
stdlib.
"""

import io
import json
import wave
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest
from fastapi.testclient import TestClient

from adapters.telnyx import TelnyxConfig, create_app
from adapters.telnyx.builder import (
    TelnyxRecordingData,
    TelnyxVconBuilder,
    _is_telnyx_host,
)

FROM_NUMBER = "+15085550101"
TO_NUMBER = "+16175550102"


def wav_bytes(seconds: int = 1, rate: int = 8000) -> bytes:
    """A real, tiny, deterministic WAV. Beats committing a fixture file."""
    buf = io.BytesIO()
    with wave.open(buf, "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(rate)
        w.writeframes(b"\x00\x01" * rate * seconds)
    return buf.getvalue()


@pytest.fixture
def recording_event():
    """A `call.recording.saved` shaped like Telnyx's documented payload."""
    return {
        "data": {
            "event_type": "call.recording.saved",
            "id": "evt-1",
            "occurred_at": "2026-09-09T18:00:05Z",
            "payload": {
                "call_control_id": "v3:abc123",
                "call_leg_id": "leg-1",
                "call_session_id": "sess-1",
                "connection_id": "conn-1",
                "recording_id": "rec-1",
                "recording_urls": {
                    "wav": "https://api.telnyx.com/v2/recordings/rec-1.wav",
                    "mp3": "https://api.telnyx.com/v2/recordings/rec-1.mp3",
                },
                "channels": "dual",
                "duration_millis": 1000,
                "from": FROM_NUMBER,
                "to": TO_NUMBER,
                "direction": "incoming",
                "start_time": "2026-09-09T18:00:00Z",
            },
        }
    }


@pytest.fixture
def audio_response():
    """Patch the recording download to serve real WAV bytes."""
    response = MagicMock()
    response.content = wav_bytes()
    response.status_code = 200
    response.raise_for_status = MagicMock()
    with patch("adapters.telnyx.builder.requests.get", return_value=response):
        yield response


@pytest.fixture
def built_vcon(recording_event, audio_response):
    """The vCon the real builder produces from that event."""
    builder = TelnyxVconBuilder(
        download_recordings=True, recording_format="wav", api_key="test-key"
    )
    vcon = builder.build(TelnyxRecordingData(recording_event))
    assert vcon is not None, "builder returned None"
    return vcon


# -- the vCon itself -------------------------------------------------------


def test_vcon_is_spec_valid(built_vcon):
    """The acceptance criterion for CON-844.

    Regression guard for the `mimetype` vs `mediatype` bug: `core/base_builder`
    passed the non-spec `mimetype`, so vcon-lib's validator rejected every vCon
    every adapter in this monorepo produced.
    """
    valid, errors = built_vcon.is_valid()
    assert valid, f"vCon failed spec validation: {errors}"


def test_dialog_carries_mediatype_not_mimetype(built_vcon):
    dialog = built_vcon.to_dict()["dialog"][0]
    assert dialog.get("mediatype") == "audio/wav"
    assert "mimetype" not in dialog, "non-spec field is back"


def test_syntax_version_is_core_02(built_vcon):
    assert built_vcon.to_dict()["vcon"] == "0.4.0"


def test_both_parties_present_as_tel_uris(built_vcon):
    tels = [p.get("tel") for p in built_vcon.to_dict()["parties"]]
    assert tels == [FROM_NUMBER, TO_NUMBER]


def test_audio_is_embedded_and_decodes(built_vcon):
    """A dialog that claims base64 audio should actually contain a WAV."""
    import base64

    dialog = built_vcon.to_dict()["dialog"][0]
    assert dialog["encoding"] == "base64"
    raw = base64.b64decode(dialog["body"])
    assert raw[:4] == b"RIFF" and raw[8:12] == b"WAVE", "body is not a WAV"


def test_duration_converted_from_millis(built_vcon):
    assert built_vcon.to_dict()["dialog"][0]["duration"] == 1.0


def test_inbound_call_originates_from_callee(built_vcon):
    """Telnyx `incoming` means they called us, so party 1 initiated."""
    assert built_vcon.to_dict()["dialog"][0]["originator"] == 1


def test_telnyx_identifiers_are_preserved(built_vcon):
    """Correlating a vCon back to the call requires these to survive."""
    tags = built_vcon.to_dict()["attachments"][0]["body"]
    assert "telnyx_call_session_id:sess-1" in tags
    assert "telnyx_call_control_id:v3:abc123" in tags
    assert "recording_channels:dual" in tags


def test_vcon_has_no_lawful_basis_unless_one_is_configured(built_vcon):
    """CON-814. Absent is the correct default, not an oversight.

    A fabricated consent record asserts something about a data subject that
    nobody established, which is worse than no record at all. So the builder
    emits nothing and logs a warning until a deployment configures a basis.
    """
    assert built_vcon.find_lawful_basis_attachments() == []


def test_configured_lawful_basis_is_emitted_and_valid(real_event, dual_channel_wav):
    from core.lawful_basis import LawfulBasisConfig

    vcon = _build(
        real_event,
        dual_channel_wav,
        lawful_basis=LawfulBasisConfig(
            lawful_basis="legitimate_interests",
            purposes=["recording", "transcription"],
        ),
    )

    found = vcon.find_lawful_basis_attachments()
    assert len(found) == 1
    assert "lawful_basis" in vcon.to_dict()["extensions"]
    assert vcon.is_valid()[0]

    assert isinstance(found[0]["body"], str), "body must be a JSON string, not an object"
    body = json.loads(found[0]["body"])
    assert body["lawful_basis"] == "legitimate_interests"
    assert [g["purpose"] for g in body["purpose_grants"]] == [
        "recording",
        "transcription",
    ]
    assert all(g["granted"] for g in body["purpose_grants"])


# -- through the webhook ---------------------------------------------------


def test_webhook_posts_a_valid_vcon_to_the_conserver(
    recording_event, audio_response, monkeypatch, tmp_path
):
    """The whole BYOK loop, minus Telnyx itself.

    Unlike `test_webhook.py`, the builder is real here; only the outbound post is
    captured, so this asserts on the vCon that would actually reach the conserver.
    """
    monkeypatch.setenv("CONSERVER_URL", "http://conserver.test")
    monkeypatch.setenv("VALIDATE_TELNYX_WEBHOOK", "false")
    # Isolate the dedupe state. Without this the tracker picks up whatever
    # `.telnyx_adapter_state.json` is lying in the working directory and skips
    # `rec-1` as already processed, which passes alone and fails in a full run.
    monkeypatch.setenv("STATE_FILE", str(tmp_path / "state.json"))

    posted = []
    with patch("adapters.telnyx.webhook.HttpPoster") as poster_cls:
        poster = MagicMock()
        poster.post.side_effect = lambda v: (posted.append(v), True)[1]
        poster_cls.return_value = poster

        client = TestClient(create_app(TelnyxConfig()))
        response = client.post("/webhook/recording", json=recording_event)

    assert response.status_code == 200
    assert len(posted) == 1, "exactly one vCon should have been posted"

    valid, errors = posted[0].is_valid()
    assert valid, f"the vCon sent to the conserver is not spec-valid: {errors}"


# -- against a real captured Telnyx payload --------------------------------
#
# `fixtures/call_recording_saved.json` is a genuine `call.recording.saved` from
# a live call on 2026-09-09 (CON-844), AWS signature redacted. Every assertion
# below encodes something the documentation did not tell us.

FIXTURE = Path(__file__).parent / "fixtures" / "call_recording_saved.json"


@pytest.fixture
def real_event():
    return json.loads(FIXTURE.read_text())


def test_recording_url_is_presigned_s3_not_telnyx(real_event):
    """The recording does not live on Telnyx's API host."""
    data = TelnyxRecordingData(real_event)
    assert "s3.amazonaws.com" in data.recording_url
    assert "X-Amz-Signature" in data.recording_url
    assert not _is_telnyx_host(data.recording_url)


def test_api_key_is_never_sent_to_a_presigned_url(real_event):
    """Security: the bearer token is the *customer's* Telnyx key under BYOK.

    Sending it to s3.amazonaws.com leaks their credential to a third party, and
    S3 rejects a request carrying both a presigned signature and an
    Authorization header, so live downloads returned 400 (verified against the
    real URL: 400 with the key, 200 without).
    """
    captured = {}

    def fake_get(url, headers=None, timeout=None, **kw):
        captured["headers"] = headers or {}
        r = MagicMock()
        r.content = wav_bytes()
        r.status_code = 200
        r.raise_for_status = MagicMock()
        return r

    with patch("adapters.telnyx.builder.requests.get", side_effect=fake_get):
        TelnyxVconBuilder(True, "wav", "super-secret-key").build(TelnyxRecordingData(real_event))

    assert (
        "Authorization" not in captured["headers"]
    ), "the customer's API key was sent to a third-party host"


def test_api_key_is_still_sent_to_telnyx_hosts():
    assert _is_telnyx_host("https://api.telnyx.com/v2/recordings/x.wav")
    assert not _is_telnyx_host("https://s3.amazonaws.com/x.wav")
    assert not _is_telnyx_host("https://api.telnyx.com.evil.test/x.wav")


def test_duration_derived_from_timestamps(real_event):
    """The real payload has no `duration_millis`, only start/end timestamps."""
    payload = real_event["data"]["payload"]
    assert "duration_millis" not in payload
    assert TelnyxRecordingData(real_event).duration_seconds == pytest.approx(19.331)


def test_real_payload_carries_no_party_identity(real_event):
    """Documents why CON-803 is required rather than a nice-to-have.

    `call.recording.saved` has no `from`, `to`, or `direction`. Those appear
    only on the lifecycle events, so a recording event alone cannot produce a
    vCon that says who was on the call.
    """
    payload = real_event["data"]["payload"]
    assert "from" not in payload
    assert "to" not in payload
    assert "direction" not in payload

    data = TelnyxRecordingData(real_event)
    assert data.from_number == ""
    assert data.to_number == ""


# -- thin vCons: external media --------------------------------------------
#
# Embedding base64 audio makes a vCon ~1.3x the size of the recording. A `url`
# plus a `content_hash` is ~800x smaller and stays verifiable. For Telnyx it is
# not merely preferable: the source URL expires in 600s, so a vCon that
# references it directly has a dead link within ten minutes.


@pytest.fixture
def dual_channel_wav():
    """~19s of dual-channel 8kHz, the shape of a real Telnyx recording."""
    buf = io.BytesIO()
    with wave.open(buf, "wb") as w:
        w.setnchannels(2)
        w.setsampwidth(2)
        w.setframerate(8000)
        w.writeframes(bytes(2 * 2 * 8000 * 19))
    return buf.getvalue()


def _build(event, audio, **kwargs):
    response = MagicMock()
    response.content = audio
    response.status_code = 200
    response.raise_for_status = MagicMock()
    with patch("adapters.telnyx.builder.requests.get", return_value=response):
        return TelnyxVconBuilder(recording_format="wav", api_key="k", **kwargs).build(
            TelnyxRecordingData(event)
        )


def test_publisher_replaces_inline_audio_with_url_and_hash(real_event, dual_channel_wav, tmp_path):
    from core.media_publisher import FilesystemPublisher

    vcon = _build(
        real_event,
        dual_channel_wav,
        publisher=FilesystemPublisher(destination=tmp_path, base_url="https://media.test/rec"),
    )
    dialog = vcon.to_dict()["dialog"][0]

    assert dialog["url"].startswith("https://media.test/rec/")
    assert dialog["content_hash"].startswith("sha512-")
    assert "body" not in dialog, "audio must not be inlined when publishing"
    assert "encoding" not in dialog
    assert vcon.is_valid()[0]


def test_content_hash_matches_the_audio(real_event, dual_channel_wav, tmp_path):
    """The hash has to be verifiable by whoever later fetches the URL."""
    import base64 as b64
    import hashlib

    from core.media_publisher import FilesystemPublisher

    vcon = _build(
        real_event,
        dual_channel_wav,
        publisher=FilesystemPublisher(destination=tmp_path, base_url="https://m.test"),
    )
    expected = "sha512-" + b64.urlsafe_b64encode(
        hashlib.sha512(dual_channel_wav).digest()
    ).decode().rstrip("=")
    assert vcon.to_dict()["dialog"][0]["content_hash"] == expected


def test_thin_vcon_is_dramatically_smaller(real_event, dual_channel_wav, tmp_path):
    from core.media_publisher import FilesystemPublisher

    fat = _build(real_event, dual_channel_wav, download_recordings=True)
    thin = _build(
        real_event,
        dual_channel_wav,
        publisher=FilesystemPublisher(destination=tmp_path, base_url="https://m.test"),
    )
    assert len(thin.to_json()) * 100 < len(
        fat.to_json()
    ), "external media should be orders of magnitude smaller"


def test_s3_publisher_uploads_with_the_right_key_and_type(real_event, dual_channel_wav):
    """No credentials needed: S3Publisher takes an injected client."""
    from core.media_publisher import S3Publisher

    seen = {}

    class FakeS3:
        def upload_file(self, Filename=None, Bucket=None, Key=None, ExtraArgs=None, **kw):
            seen.update(bucket=Bucket, key=Key, extra=ExtraArgs)

    vcon = _build(
        real_event,
        dual_channel_wav,
        publisher=S3Publisher(
            bucket="vconic-media",
            prefix="telnyx",
            base_url="https://vconic-media.nyc3.digitaloceanspaces.com",
            client=FakeS3(),
        ),
    )

    assert seen["bucket"] == "vconic-media"
    assert seen["key"].startswith("telnyx/")
    assert seen["extra"]["ContentType"] == "audio/wav"
    assert vcon.to_dict()["dialog"][0]["url"].startswith(
        "https://vconic-media.nyc3.digitaloceanspaces.com/telnyx/"
    )


def test_reference_url_does_not_mangle_a_presigned_telnyx_url(real_event):
    """Regression: the base builder appends `.wav` to select a Twilio format.

    Doing that to a Telnyx URL lands the suffix after the AWS query string and
    produces a link that cannot resolve.
    """
    vcon = _build(real_event, b"", download_recordings=False)
    url = vcon.to_dict()["dialog"][0]["url"]
    assert "X-Amz-Signature" in url
    assert not url.endswith(".wav"), "extension appended after the query string"
